name: 'hack'
description: 'hack'

outputs:
  sarif:
    description: 'SARIF output'

runs:
  using: docker
  image: docker://presidentbeef/brakeman
  entrypoint: "find / -name entrypoint.sh"
